# Generated by Django 5.2.10 on 2026-01-26 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Номер заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_url",
            field=models.URLField(
                blank=True,
                help_text="Ссылка на страницу оплаты",
                max_length=500,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_payment", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("processing", "В обработке"),
                    ("shipped", "Отправлен"),
                    ("delivered", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                default="awaiting_payment",
                help_text="Текущее состояние заказа",
                max_length=50,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Сумма всех товаров в заказе",
                max_digits=10,
                verbose_name="Общая сумма заказа",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustomer",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Пожелания клиента к заказу",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustomer",
            name="email",
            field=models.EmailField(
                help_text="Для отправки уведомлений",
                max_length=254,
                verbose_name="Email клиента",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustomer",
            name="full_name",
            field=models.CharField(
                help_text="ФИО получателя",
                max_length=200,
                verbose_name="Полное имя клиента",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustomer",
            name="phone",
            field=models.CharField(
                help_text="Для связи по доставке",
                max_length=20,
                verbose_name="Телефон клиента",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustomer",
            name="shipping_address",
            field=models.TextField(
                help_text="Полный адрес с индексом", verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена на момент оформления заказа",
                max_digits=10,
                verbose_name="Цена за 1 шт.",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="main.productvariant",
                verbose_name="Товар (размер)",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                help_text="Сколько единиц товара заказано",
                verbose_name="Количество штук",
            ),
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("order_created", "Резерв при создании заказа"),
                            ("order_paid", "Списание при оплате заказа"),
                            ("order_canceled", "Возврат при отмене заказа"),
                            ("manual_adjustment", "Ручная корректировка"),
                            ("restock", "Пополнение склада"),
                        ],
                        max_length=50,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Отрицательное - списание, положительное - пополнение",
                        verbose_name="Изменение количества",
                    ),
                ),
                (
                    "stock_before",
                    models.PositiveIntegerField(
                        help_text="Количество на складе до изменения",
                        verbose_name="Остаток до",
                    ),
                ),
                (
                    "stock_after",
                    models.PositiveIntegerField(
                        help_text="Количество на складе после изменения",
                        verbose_name="Остаток после",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация",
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заказ, связанный с этим изменением",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_changes",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_history",
                        to="main.productvariant",
                        verbose_name="Вариант товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "История остатков",
                "verbose_name_plural": "История остатков",
                "db_table": "stock_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_variant", "-created_at"],
                        name="stock_histo_product_a4bfff_idx",
                    ),
                    models.Index(
                        fields=["order"], name="stock_histo_order_i_4f9334_idx"
                    ),
                ],
            },
        ),
    ]
