# Generated by Django 5.2.10 on 2026-01-14 16:05

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=django.db.models.fields.UUIDField,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID заказа",
            ),
        ),
    ]
