# Generated by Django 5.2.10 on 2026-01-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_order_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ клиента', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordercustomer',
            options={'verbose_name': 'Клиент (информация)', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция в заказе', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись в истории остатков', 'verbose_name_plural': 'История остатков'},
        ),
    ]
