# Generated by Django 5.2.10 on 2026-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_ordercustomer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость доставки в рублях', max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('time_interval', 'До двери'), ('self_pickup', 'Самовывоз из ПВЗ')], default='time_interval', help_text='Выбранный способ доставки', max_length=50, verbose_name='Способ доставки'),
        ),
    ]
