# Generated by Django 5.2.10 on 2026-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_ordercustomer_city_alter_ordercustomer_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
