# Generated by Django 5.2.10 on 2026-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_cost_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('time_interval', 'До двери'), ('self_pickup', 'Самовывоз из ПВЗ')], default='self_pickup', help_text='Выбранный способ доставки', max_length=50, verbose_name='Способ доставки'),
        ),
    ]
