# Generated by Django 5.2.10 on 2026-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Для ответа', max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Суть обращения')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('handled', 'Обработан')], default='new', verbose_name='Статус обращения')),
            ],
        ),
    ]
