# Generated by Django 5.2.10 on 2026-02-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
    ]
