# Generated by Django 5.2.10 on 2026-01-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Свитшоты, Куртки, Футболки",
                        max_length=100,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Будет сгенерирован автоматически",
                        unique=True,
                        verbose_name="URL (латиницей)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Черный, Белый, Молочный",
                        max_length=50,
                        unique=True,
                        verbose_name="Название цвета",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Будет сгенерирован автоматически",
                        unique=True,
                        verbose_name="URL (латиницей)",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
                "db_table": "colors",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: PUFFER JACKET gen 2",
                        max_length=250,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Будет сгенерирован автоматически",
                        unique=True,
                        verbose_name="URL (латиницей)",
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Показывается в карточке товара в каталоге",
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание товара",
                        verbose_name="Полное описание",
                    ),
                ),
                (
                    "materials",
                    models.TextField(
                        blank=True,
                        help_text="Например: 100% хлопок, пенополиуретан",
                        verbose_name="Состав и материалы",
                    ),
                ),
                (
                    "care_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Например: Стирать при 30°, не отбеливать, гладить при низкой температуре",
                        verbose_name="Уход за изделием",
                    ),
                ),
                (
                    "size_chart",
                    models.TextField(
                        blank=True,
                        help_text="Таблица размеров для этого товара",
                        verbose_name="Размерная сетка",
                    ),
                ),
                (
                    "delivery_info",
                    models.TextField(
                        blank=True,
                        help_text="Сроки и условия доставки",
                        verbose_name="Информация о доставке",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Группа товаров",
                "verbose_name_plural": "Группы товаров",
                "db_table": "product_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: XS, S, M, L, XL, XXL",
                        max_length=10,
                        unique=True,
                        verbose_name="Размер",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше в списке",
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Использовать"),
                ),
            ],
            options={
                "verbose_name": "Размер",
                "verbose_name_plural": "Размеры",
                "db_table": "sizes",
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: PUFFER JACKET gen 2 washed black",
                        max_length=250,
                        verbose_name="Полное название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Будет сгенерирован автоматически из названия",
                        unique=True,
                        verbose_name="URL (латиницей)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена для всех размеров, если не указана индивидуальная",
                        max_digits=10,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Показывать на сайте"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "color",
                    models.ForeignKey(
                        help_text="Выберите цвет",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="main.color",
                        verbose_name="Цвет товара",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Выберите товар из списка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="main.productgroup",
                        verbose_name="Базовый товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroupCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_groups",
                        to="main.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_categories",
                        to="main.productgroup",
                        verbose_name="Группа товаров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория группы товаров",
                "verbose_name_plural": "Категории групп товаров",
                "db_table": "product_group_categories",
            },
        ),
        migrations.AddField(
            model_name="productgroup",
            name="categories",
            field=models.ManyToManyField(
                related_name="product_groups",
                through="main.ProductGroupCategory",
                to="main.category",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Будет сгенерирован автоматически",
                        max_length=100,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Оставьте пустым, если цена такая же как у товара",
                        max_digits=10,
                        null=True,
                        verbose_name="Цена для этого размера",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для заказа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        help_text="Выберите размер из списка",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="main.size",
                        verbose_name="Размер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товара",
                "db_table": "product_variants",
                "ordering": ["size"],
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        max_length=50,
                        verbose_name="Тип медиа",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Основное"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="main.productvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиа товара",
                "verbose_name_plural": "Медиа товара",
                "db_table": "product_media",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["group", "color"], name="products_group_i_b38253_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("group", "color")},
        ),
        migrations.AddIndex(
            model_name="productgroupcategory",
            index=models.Index(
                fields=["group", "category"], name="product_gro_group_i_eabc1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productgroupcategory",
            unique_together={("group", "category")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "size"], name="product_var_product_3284f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "size")},
        ),
    ]
