# Generated by Django 5.2.10 on 2026-01-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="optionvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="main.option",
                verbose_name="Опция",
            ),
        ),
        migrations.AlterField(
            model_name="optionvalue",
            name="value",
            field=models.CharField(max_length=100, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="excerpt",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_products",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_categories",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productcontent",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="productcontent",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="productcontent",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productcontent",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="productcontent",
            name="type",
            field=models.CharField(
                choices=[
                    ("care", "Care"),
                    ("size_chart", "Size Chart"),
                    ("materials", "Materials"),
                    ("delivery", "Delivery Information"),
                ],
                max_length=50,
                verbose_name="Тип содержания",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основное"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                max_length=50,
                verbose_name="Тип медиа",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="main.productvariant",
                verbose_name="Вариант",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="main.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Артикул"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="Остаток"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterField(
            model_name="variantoptionvalue",
            name="option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_options",
                to="main.optionvalue",
                verbose_name="Значение опции",
            ),
        ),
        migrations.AlterField(
            model_name="variantoptionvalue",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_values",
                to="main.productvariant",
                verbose_name="Вариант",
            ),
        ),
    ]
