# Generated by Django 5.2.10 on 2026-01-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Цвет (справочник)', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар в продаже (с цветом)', 'verbose_name_plural': 'Товары в продаже'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'verbose_name': 'Базовый товар (без цвета)', 'verbose_name_plural': 'Базовые товары'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии и медиа'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size'], 'verbose_name': 'Размер и остаток', 'verbose_name_plural': 'Размеры и остатки'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Размер (справочник)', 'verbose_name_plural': 'Размеры'},
        ),
    ]
