# Generated by Django 5.2.10 on 2026-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='dimension_height',
            field=models.PositiveIntegerField(default=10, help_text='Высота упаковки в сантиметрах', verbose_name='Высота (см)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimension_length',
            field=models.PositiveIntegerField(default=30, help_text='Длина упаковки в сантиметрах', verbose_name='Длина (см)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimension_width',
            field=models.PositiveIntegerField(default=20, help_text='Ширина упаковки в сантиметрах', verbose_name='Ширина (см)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.PositiveIntegerField(default=500, help_text='Вес одной единицы товара в граммах', verbose_name='Вес (грамм)'),
        ),
    ]
