# Generated by Django 5.2.10 on 2026-01-14 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0004_alter_ordercustomer_city_alter_ordercustomer_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=100, verbose_name="Провайдер платежа"),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        max_length=100, verbose_name="ID платежа у провайдера"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата платежа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("completed", "Завершен"),
                            ("failed", "Неудачный"),
                            ("refunded", "Возвращен"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Статус платежа",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "db_table": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Тип события"),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата события"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Данные события")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="payment.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие платежа",
                "verbose_name_plural": "События платежей",
                "db_table": "payment_events",
                "ordering": ["-event_date"],
            },
        ),
    ]
