# Generated by Django 5.2.10 on 2026-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_ordercustomer_city_alter_ordercustomer_comment"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="ID платежа у провайдера",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("succeeded", "Завершен"),
                    ("canceled", "Отменен"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["-payment_date"], name="payments_payment_f51455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["payment", "event_type"], name="payment_eve_payment_35ff13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentevent",
            index=models.Index(
                fields=["-event_date"], name="payment_eve_event_d_67a0c8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.UniqueConstraint(
                fields=("payment", "event_type"), name="unique_payment_event"
            ),
        ),
    ]
