# Generated by Django 5.2.10 on 2026-01-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Платеж клиента', 'verbose_name_plural': 'Платежи'},
        ),
    ]
